class CreateRfps < ActiveRecord::Migration[5.1]
  def change
    create_table :rfps do |t|
    	t.string :pbm
    	t.string :name
    	t.string :eff_date
    	t.string :network
    	t.string :prep
    	t.string :carrier
    	t.decimal :inbenefits
    	t.decimal :indeductable
    	t.string :incoinsurance
    	t.decimal :inoop
    	t.decimal :inoffice_visit
    	t.decimal :inspecialist
    	t.decimal :inlab_xray
    	t.decimal :inpreventative
    	t.decimal :inteladoc
    	t.decimal :inurgent_care
    	t.decimal :inprescription
    	t.decimal :iner
    	t.decimal :outbenefits
    	t.decimal :outdeductable
    	t.string :outcoinsurance
    	t.decimal :outoop
    	t.decimal :outoffice_visit
    	t.decimal :outspecialist
    	t.decimal :outlab_xray
    	t.decimal :outpreventative
    	t.decimal :outteladoc
    	t.decimal :outurgent_care
    	t.decimal :outprescription
    	t.decimal :outer
    	t.decimal :administrator
    	t.decimal :ahdi
    	t.decimal :urcm
    	t.decimal :ppo
    	t.decimal :stop_loss
    	t.decimal :teladoc_consult
    	t.decimal :lab_card
    	t.decimal :hipaa
    	t.decimal :broker_fee
    	t.decimal :other_fee
    	t.decimal :total_admin
    	t.string :plan_platform
    	t.decimal :specific_deductable
    	t.decimal :mar
    	t.decimal :mlr
    	t.integer :employee
    	t.decimal :inempfee
    	t.decimal :outempfee
    	t.integer :ee_sp
    	t.decimal :inee_spfee
    	t.decimal :outee_spfee
    	t.integer :ee_child
    	t.decimal :inee_childfee
    	t.decimal :outee_childfee
    	t.integer :family
    	t.decimal :infamilyfee
    	t.decimal :outfamilyfee
    	t.decimal :intransplant
    	t.decimal :outtransplant
    	t.decimal :inmac
    	t.decimal :outmac
    	t.decimal :inagg_premium
    	t.decimal :outagg_premium
    	t.decimal :intpsp
    	t.decimal :inmfct
    	t.decimal :outtpsp
    	t.decimal :outmfct
    	t.integer :employee2
    	t.decimal :inempfee2
    	t.decimal :outempfee2
    	t.integer :ee_sp2
    	t.decimal :inee_spfee2
    	t.decimal :outee_spfee2
    	t.integer :ee_child2
    	t.decimal :inee_childfee2
    	t.decimal :outee_childfee2
    	t.integer :family2
    	t.decimal :infamilyfee2
    	t.decimal :outfamilyfee2
    	t.integer :total
    	t.decimal :intotal
    	t.decimal :outtotal
    	t.decimal :intmal
    	t.decimal :outtmal
    	t.decimal :intafc
    	t.decimal :outtfac
    	t.decimal :intaal
    	t.decimal :outtall
    	t.decimal :inmax_total
    	t.decimal :outmax_total
    	t.decimal :inempsum
    	t.decimal :outempsum
    	t.decimal :inee_spsum
    	t.decimal :outee_spsum
    	t.decimal :inee_childsum
    	t.decimal :outee_childsum
    	t.decimal :infamilysum
    	t.decimal :outfamilysum
    	t.decimal :startup
    	t.decimal :sbc
    	t.decimal :annual_fee
    	t.decimal :plan_document
    	t.decimal :totalfees

      t.timestamps
    end
  end
end
